#define BLINK_PIN GPIO_NUM_2

#define PIN_CLK GPIO_NUM_21
#define PIN_SDA GPIO_NUM_22

#define VESC_RX_PIN GPIO_NUM_16
#define VESC_TX_PIN GPIO_NUM_17
#define VESC_PORT UART_NUM_2  

#define BALANCE_REFERENCE_CHANNEL ADC2_CHANNEL_0
#define BALANCE_REFERENCE_PIN GPIO_NUM_4

#define ENABLE_PIN GPIO_NUM_15
